version: '3.7'

services:
  go:
    image: 'golang:${GO_IMAGE_TAG:-alpine}'
    container_name: go_cli
    network_mode: host
    working_dir: /go/src/app
    volumes:
      - .:/go/src/app
    entrypoint: go
